<?php

/**
 * @file
 * Provides rork.nl customization for the CKEditor WYSIWYG editor CodeSnippet plugin.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 * Add extra languages for CodeSnippet 
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function rorknlcodesnippet_form_filter_format_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['editor']['settings']['subform']['plugins']['codesnippet'])) {
    $form['editor']['settings']['subform']['plugins']['codesnippet']['highlight_languages']['#options']['plaintext'] = 'Plaintext';
    $form['editor']['settings']['subform']['plugins']['codesnippet']['highlight_languages']['#options']['yaml'] = 'YAML';
    $form['editor']['settings']['subform']['plugins']['codesnippet']['highlight_languages']['#options']['lua'] = 'Lua';

    asort($form['editor']['settings']['subform']['plugins']['codesnippet']['highlight_languages']['#options'], SORT_STRING | SORT_FLAG_CASE);
  }
}